In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/BDI/monster_com-job_sample.csv')

In [ ]:
df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [ ]:
df.shape

(22000, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          22000 non-null  object
 1   country_code     22000 non-null  object
 2   date_added       122 non-null    object
 3   has_expired      22000 non-null  object
 4   job_board        22000 non-null  object
 5   job_description  22000 non-null  object
 6   job_title        22000 non-null  object
 7   job_type         20372 non-null  object
 8   location         22000 non-null  object
 9   organization     15133 non-null  object
 10  page_url         22000 non-null  object
 11  salary           3446 non-null   object
 12  sector           16806 non-null  object
 13  uniq_id          22000 non-null  object
dtypes: object(14)
memory usage: 2.3+ MB

In [ ]:
print("Unique values in each column\n")

for col in df:
  print(f"{col} count -> {len(pd.unique(df[col]))} ")

Unique values in each column

country count -> 1
country_code count -> 1
date_added count -> 79
has_expired count -> 1
job_board count -> 1
job_description count -> 18744
job_title count -> 18759
job_type count -> 40
location count -> 8423
organization count -> 739
page_url count -> 22000
salary count -> 1738
sector count -> 164
uniq_id count -> 22000

In [ ]:
print("MISSING VALS IN EACH COLUMN\n")
df.isna().sum()

MISSING VALS IN EACH COLUMN

country                0
country_code           0
date_added         21878
has_expired            0
job_board              0
job_description        0
job_title              0
job_type            1628
location               0
organization        6867
page_url               0
salary             18554
sector              5194
uniq_id                0
dtype: int64

### since country, country_code, has_expired, job_board has only 1 unique value we will drop this col

In [ ]:
df = df.drop(columns=['country','country_code','has_expired','job_board'],axis=1)

### page_url & uniq_id is not required for analysis

In [ ]:
df = df.drop(columns=['page_url','uniq_id'],axis=1)

In [ ]:
df.describe()

,date_added,job_description,job_title,job_type,location,organization,salary,sector
count,122,22000,22000,20372,22000,15133,3446,16806
unique,78,18744,18759,39,8423,738,1737,163
top,9/22/2016,12N Horizontal Construction Engineers Job Desc...,Monster,Full Time,"Dallas, TX",Healthcare Services,"40,000.00 - 100,000.00 $ /year",Experienced (Non-Manager)
freq,6,104,318,6757,646,1919,50,4594

### Cleaning job_type

In [ ]:
df.job_type.unique()

array(['Full Time Employee', 'Full Time', 'Full Time, Employee',
       'Part Time Employee', nan, 'Full Time Temporary/Contract/Project',
       'Full Time , Employee', 'Full Time, Temporary/Contract/Project',
       'Employee', 'Part Time', 'Part Time, Employee', 'Full Time Intern',
       'Temporary/Contract/Project', 'Full Time / Employee',
       'Full Time , Temporary/Contract/Project',
       'Part Time, Temporary/Contract/Project', 'Full Time/ Employee',
       'Per Diem, Employee', 'Job Type Full Time Employee', 'Per Diem',
       'Full Time\xa0', 'Part Time Intern', 'Per Diem Employee',
       'Part Time/ Temporary/Contract/Project',
       'Part Time Temporary/Contract/Project', 'Exempt',
       'Part Time , Temporary/Contract/Project', 'Full Time\xa0 Employee',
       'Part Time Seasonal', 'Part Time , Employee', 'Job Type Employee',
       'Job Type Full Time Temporary/Contract/Project',
       'Full Time / > Employee', 'Part Time\xa0',
       'Per Diem, Temporary/Contract/Project',
       'Full Time / Temporary/Contract/Project', 'Part Time, Intern',
       'Job Type Full Time', 'Part Time / Employee',
       'Job Type Part Time Employee'], dtype=object)

In [ ]:
df2 = df

In [ ]:
job_type = df2['job_type'].str.replace('\xa0','').str.split(",")
df2['job_type'] = job_type.str[0]

In [ ]:
df['job_type'][df['job_type']=='Full Time Employee']='Full Time'
df['job_type'][df['job_type']=='Part Time Employee']='Part Time'

In [ ]:
df2.job_type.unique()

array(['Full Time', 'Part Time', nan,
       'Full Time Temporary/Contract/Project', 'Full Time ', 'Employee',
       'Full Time Intern', 'Temporary/Contract/Project',
       'Full Time / Employee', 'Full Time/ Employee', 'Per Diem',
       'Job Type Full Time Employee', 'Part Time Intern',
       'Per Diem Employee', 'Part Time/ Temporary/Contract/Project',
       'Part Time Temporary/Contract/Project', 'Exempt', 'Part Time ',
       'Part Time Seasonal', 'Job Type Employee',
       'Job Type Full Time Temporary/Contract/Project',
       'Full Time / > Employee', 'Full Time / Temporary/Contract/Project',
       'Job Type Full Time', 'Part Time / Employee',
       'Job Type Part Time Employee'], dtype=object)

### location

In [ ]:
df3 = df2

In [ ]:
df2.location.unique()

In [ ]:
df3 = df3[df3['location'].apply(lambda x: len(x)<20)]
df3['location'] = df3['location'].str.split(',').str[0]

<ipython-input-92-966f322866c9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['location'] = df3['location'].str.split(',').str[0]

In [ ]:
df3.location.unique()

array(['Madison', 'Dixon', 'Camphill', ..., 'Cincinnati 45203',
       'Edgewood', 'Sharonville'], dtype=object)

In [ ]:
df3.head()

,date_added,job_description,job_title,job_type,location,organization,salary,sector
0,NaN,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time,Madison,NaN,NaN,IT/Software Development
1,NaN,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,Madison,Printing and Publishing,NaN,NaN
3,NaN,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,Dixon,Altec Industries,NaN,Experienced (Non-Manager)
4,NaN,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time,Camphill,Retail,NaN,Project/Program Management
5,NaN,Job Description Job #: 720298Apex Systems has...,Construction PM - Charlottesville Job in Charl...,Full Time,Charlottesville,Computer/IT Services,NaN,Experienced (Non-Manager)